import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Header, Footer, Whatsapp } from '@/components'

const poppins = Poppins({
    weight: ['300', '400', '700']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className}`}>
                <Header />
                <main>{children}</main>
                <Footer />
                <Whatsapp />
            </body>
        </html>
    )
}
