export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Whatsapp } from './Whatsapp'
export { default as Filter } from './Filter'
export { default as Gallery } from './Gallery'
export { default as Faqs } from './Faqs'
