name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Create .env file from secrets
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: 3. Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 4. Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: 5. Cache Next.js build
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: 6. Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 7. Build and export static files
        run: pnpm run build

      - name: 8. Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: 9. Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

